<?php /** @var \Punchout2Go\HyvaCompat\Block\Config $block */ ?>
<?php $helper = $this->helper(\Punchout2Go\Punchout\Helper\Transfer::class); ?>
<script type="module">
document.addEventListener('DOMContentLoaded', () => {
  Promise.all([
    import('<?= $block->getViewFileUrl("Punchout2Go_HyvaCompat::js/punchout-session.js") ?>'),
    import('<?= $block->getViewFileUrl("Punchout2Go_HyvaCompat::js/punchout-transfer.js") ?>')
  ]).then(() => {
	console.log('[Punchout2Go_HyvaCompat] - <?= $helper->getIsJsLogging() ?>' );
	if (<?= $helper->getIsJsLogging() ?>) {
		console.log('[Punchout2Go_HyvaCompat] Session & Transfer modules loaded.');
	}
    window.P2G_HYVA = window.P2G_HYVA || {};
    window.P2G_HYVA.restStoreCode = '<?= $block->escapeHtml($block->getRestStoreCode()) ?>';
    window.P2G_HYVA.closePostUrl = '<?= $block->escapeUrl($block->getClosePostUrl()) ?>';
    window.P2G_HYVA.apiKey = '<?= $block->escapeHtml($block->getApiKey()) ?>';
    window.__P2G_TRACE = [];
  }).catch(err => console.error('Punchout2Go_HyvaCompat load failed:', err));
});
</script>
